apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fleet-pulse

resources:
  - namespace.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - postgres/secret.yaml
  - auth-service/deployment.yaml
  - auth-service/service.yaml
  - auth-service/configmap.yaml
  - auth-service/secret.yaml